import type { Metadata } from 'next';
import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import './globals.css';
import Header from '@common/components/layout/header/Header';
import Footer from '@/common/components/layout/footer/Footer';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});
const montserrat = Montserrat({
	weight: ['400', '500', '600', '800', '900'], // Definir los pesos que necesitas
	subsets: ['latin'],
	variable: '--font-montserrat',
});
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es" suppressHydrationWarning>
			<body
				className={`${montserrat.className} ${geistSans.variable} ${geistMono.variable} min-h-screen antialiased`}
			>
				<Header />

				<main className="flex-1">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
